language: c

# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - NimBinaries
    - rocksdbCache

git:
  # when multiple CI builds are queued, the tested commit needs to be in the last X commits cloned with "--depth X"
  depth: 10

matrix:
  include:
    # Build and test using both gcc and clang
    # For faster testing we don't test clang on linux, only on macOS
    - os: linux
      compiler: gcc
      sudo: required
      before_install:
        - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
    - os: osx
      compiler: clang
      before_install:
        - launchctl setenv LIBRARY_PATH /usr/local/lib # for RocksDB

install:
  # build nim from our own branch - this to avoid the day-to-day churn and
  # regressions of the fast-paced Nim development while maintaining the
  # flexibility to apply patches
  - curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus/devel/build_nim.sh
  - env MAKE="make -j2" bash build_nim.sh Nim csources dist/nimble NimBinaries
  - export PATH=$PWD/Nim/bin:$PATH

  # build our own rocksdb to test with a fixed version that we think works
  - curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus/devel/build_rocksdb.sh
  - bash build_rocksdb.sh rocksdbCache

script:
  - nimble install -y
  - nimble test

branches:
  except:
    - gh-pages
